// File ids
type RSS3ID = string; // Same as ethereum address
type RSS3CustomItemsListID = string; // `${RSS3ID}-list-items.custom-${index}`
type RSS3AutoItemsListID = string; // `${RSS3ID}-list-items.auto-${index}`
type RSS3LinksListID = string; // `${RSS3ID}-list-links.${links.id}-${index}`
type RSS3BacklinksListID = string; // `${RSS3ID}-list-backlinks.${backlinks.id}-${index}`
type RSS3AssetsListID = string; // `${RSS3ID}-list-assets-${index}`
type RSS3ItemBacklinksListID = string; // `${RSS3ID}-list-item.${item.index}.backlinks.${backlinks.id}-${index}`

type RSS3ItemID = RSS3CustomItemID | RSS3AutoItemID;
type RSS3CustomItemID = string; // `${RSS3ID}-item-custom-${index}`
type RSS3AutoItemID = string; // `${RSS3ID}-item-auto-${index}`
type ThirdPartyAddress = string[]; // A series of url or ipfs hash that link to an identical file

type RSS3ListID =
    | RSS3CustomItemsListID
    | RSS3AutoItemsListID
    | RSS3LinksListID
    | RSS3BacklinksListID
    | RSS3AssetsListID
    | RSS3ItemBacklinksListID;
type RSS3FileID = RSS3ID | RSS3ListID; // Unique indicate for current file
type RSS3File = RSS3Index | RSS3List;

// Common attributes for each files
interface RSS3Base {
    version: 'rss3.io/version/v0.3.1'; // Proposal version for current file. It should be like `rss3.io/version/v1.0.0`
    id: RSS3FileID;
    date_created: string; // Specifies the created date in RFC 3339 format
    date_updated: string; // Specifies the updated date in RFC 3339 format
}

interface RSS3SignedBase extends RSS3Base {
    signature: string; // Signed by persona's private key; The signature content is the Keccak-256 hash of the array of object sorted by alphabetical and excluding objects containing `auto: true` field and the `signature` field itself(for example {a: "1", c: "2", b: {d: "3"}, e: {auto: true}} -> [["a", "1"], ["b", ["d", "3"]], ["c", "2"]]) or the string `Hi, RSS3. I'm your agent ${agent_id}` if using agent signature; Used for the object integration verification for both server side and persona side
    agent_id?: string; // A random ed25519 public key generated by the client
    agent_signature?: string; // A signature signed by `agent_id`'s private key, its content is the same as `signature`
}

interface RSS3UnsignedBase extends RSS3Base {
    auto: true;
}

// RSS3 index file, main entrance for a persona
interface RSS3Index extends RSS3SignedBase {
    id: RSS3ID;
    controller?: string; // A contract address indicating ownership of the file

    profile?: {
        name?: string;
        avatar?: ThirdPartyAddress;
        bio?: string;
        accounts?: {
            tags?: string[];
            id: string; // ${platform}-${identity}, for example, EVM+-0x1234567890123456789012345678901234567890 or Twitter-rss3_
            signature?: string; // Signature of [["address", id], ["id", account.id], ["tags", account.tags]], optional for no public-key cryptography platform
        }[];
    };

    items?: {
        custom?: RSS3CustomItemsListID;
        auto?: RSS3AutoItemsListID;
    };

    links?: {
        tags?: string[];
        id: string; // Link id, for example: follow superfollow
        list?: RSS3LinksListID; // Personas who belong to this link
    }[];

    backlinks?: {
        // Backlinks for this persona, for example: follow link's backlink means followers.
        auto: true;
        id: string; // The same as links.id
        list: RSS3BacklinksListID; // File ID of backlink list that belong to this link. See **RSS3List** for more details
    }[];

    assets?: RSS3AssetsListID;
}

// RSS3 list files, used for list of links, backlinks, contexts, items, assets
type RSS3List =
    | RSS3CustomItemsList
    | RSS3AutoItemsList
    | RSS3LinksList
    | RSS3AssetsList
    | RSS3BacklinksList
    | RSS3ItemBacklinksList;

type RSS3CustomItemsList = (RSS3SignedBase | RSS3UnsignedBase) & {
    id: RSS3CustomItemsListID;
    list?: RSS3CustomItem[];
    list_next?: RSS3CustomItemsListID;
};

type RSS3AutoItemsList = (RSS3SignedBase | RSS3UnsignedBase) & {
    id: RSS3AutoItemsListID;
    list?: RSS3AutoItem[];
    list_next?: RSS3AutoItemsListID;
};

type RSS3AssetsList = (RSS3SignedBase | RSS3UnsignedBase) & {
    id: RSS3AssetsListID;
    list?: RSS3Asset[];
    list_next?: RSS3AssetsListID;
};

type RSS3LinksList = RSS3SignedBase & {
    id: RSS3LinksListID;
    list?: RSS3ID[];
    list_next?: RSS3LinksListID;
};

type RSS3BacklinksList = RSS3UnsignedBase & {
    id: RSS3BacklinksListID;
    list?: RSS3ID[];
    list_next?: RSS3BacklinksListID;
};

type RSS3ItemBacklinksList = RSS3UnsignedBase & {
    id: RSS3ItemBacklinksListID;
    list?: RSS3ItemID[];
    list_next?: RSS3ItemBacklinksListID;
};

// Asset
type RSS3Asset = RSS3CustomAsset | RSS3AutoAsset;

interface RSS3CustomAsset {
    // A type of asset posted by persona itself
    id: string; // custom-${identity}-${type}-${id}, for example, persona's cute(q) Garage Kit(gk) (id 10035911): custom-gk-q-10035911
    tags?: string[];
}

interface RSS3AutoAsset {
    // A type of asset that is automatically generated by a node
    id: string; // ${platform}-${identity}-${type}-${id}, for example, a NFT(id 0x456.5) in the Ethereum chain owned by apersona's EVM+ account(0x123): EVM+-0x123-Ethereum.NFT-0x456.5
    auto: true;
}

// Item
interface RSS3ItemBase {
    id: RSS3ItemID;
    date_created: string; // Specifies the published date in RFC 3339 format
    date_updated: string; // Specifies the modified date in RFC 3339 format

    backlinks?: {
        // Interactive items from other personas.
        auto: true;
        id: string;
        list: RSS3ItemBacklinksListID; // File ID of items list that belong to this context. See **RSS3List** for more details
    }[];
}

interface RSS3CustomItem extends RSS3ItemBase {
    // A type of content posted by persona itself
    id: RSS3CustomItemID;
    tags?: string[];
    authors?: RSS3ID[];
    title?: string;
    summary?: string;

    link?: {
        id: string; // Link id for the non-original item, for example: comment like
        target: RSS3ItemID; // Target of the non-original item
    };

    contents?: {
        // Contents of current item, possibly multiple different types of content
        tags?: string[];
        address: ThirdPartyAddress;
        mime_type: string; // [MIME type](https://en.wikipedia.org/wiki/Media_type) of current content
        name?: string;
        size_in_bytes?: string;
        duration_in_seconds?: string;
    }[];
}

interface RSS3AutoItem extends RSS3ItemBase {
    // A type of content that is automatically generated by a node to represent a change of an asset
    id: RSS3AutoItemID;
    auto: true;

    content: {
        field: string; // 'assets-EVM+-0x123-Ethereum.NFT-0x456.5' 'links-follow', 'profile-avatar', 'profile-accounts-EVM+-0x123', etc
        action: {
            type: 'add' | 'remove' | 'update';
            payload?: string; // If the type is `add` or `remove`, then it is the added or removed content, empty means the content is itself, if the type is `update`, then it is the content after updating
        };
    };
}

type RSS3Profile = Required<RSS3Index>['profile'];
type RSS3Account = Required<RSS3Profile>['accounts'][number];
type RSS3Links = Required<RSS3Index>['links'];
